### ISSUE TITLE
Notify maintainers of similar libraries

### ISSUE THREAD

**Issue by dandv** [component/textarea-caret-position#11]
We've uncovered some cool tricks on getting the (x, y) position of the caret in a `textarea` and in the true spirit of open source, it would be nice to notify the maintainers of similar libraries. Some may choose to honorably deprecate their libraries and point users to this one; others might want to incorporate what we've learned and increase the quality of their solutions; and hopefully others will contribute to textarea-caret-position as well (we still have [some bugs](https://github.com/component/textarea-caret-position/issues/)!).

This issue will also serve as a list of how this component stacks against others in scope and [features](https://github.com/component/textarea-caret-position/#features).

StackOverflow [list of questions on textarea](http://meta.stackoverflow.com/questions/225724/set-of-exact-duplicates-on-getting-the-x-y-coordinates-of-the-caret-in-the-te):
* http://stackoverflow.com/questions/29709/how-do-i-get-the-x-y-pixel-coordinates-of-the-caret-in-text-boxes (2008-Aug)
* http://stackoverflow.com/questions/128342/display-div-at-cursor-position-in-textarea (2008-Sep)
* http://stackoverflow.com/questions/3510009/textarea-x-y-caret-coordinates-jquery-plugin/ (2010)
* http://stackoverflow.com/questions/9012835/find-caret-position-in-textarea-in-pixels (2012-Jan)
* http://stackoverflow.com/questions/18185426/how-to-find-pagex-pagey-positions-of-the-cursor-when-inside-a-textbox-using-ja (2012-Aug)
* http://stackoverflow.com/questions/12927258/float-a-div-on-a-textarea/22463060 (2012-Oct)
* http://stackoverflow.com/questions/14524696/show-toolbar-under-selected-text-with-jquery (2013-Jan)
* http://stackoverflow.com/questions/16212871/get-the-offset-position-of-the-caret-in-a-textarea-in-pixels (2013-Apr)

StackOverflow questions re. `<input type="text">`
* http://stackoverflow.com/questions/6930578/get-cursor-or-text-position-in-pixels-for-input-element/23428025#23428025
* http://stackoverflow.com/questions/13347471/caret-position-in-pixels-in-an-input-type-text-not-a-textarea#comment35903934_13347471

Google Code projects:
* https://code.google.com/p/rangy/wiki/PositionModule - Tim Down's Rangy plugin (abandoned PositionModule)

**Comment by quantuminformation** [comment]
As much as I like your demo, its a lot of code, any word on a native feature for browsers?
