### ISSUE TITLE
Bad positioning on android

### ISSUE THREAD

**Issue by gkalabin** [component/textarea-caret-position#16]
Hello!
The positioning of the red div is wrong on my android phone (my browser is google chrome). Here is a screenshot:
![2014-06-19 18 14 28](https://cloud.githubusercontent.com/assets/1110801/3328417/5e2859ae-f7bc-11e3-87b7-5f47f53aee67.png)

**Comment by dandv** [comment]
I can no longer reproduce on Chrome 55 on Android.

Closing unless someone can reproduce on a [sufficiently modern browser](http://caniuse.com/usage-table).
