### ISSUE TITLE
Could I override the carret position to get custom offsets?

### ISSUE THREAD

**Issue by Darker** [component/textarea-caret-position#18]
I'd like to calculate pixel offsets of other "carrets" than the selected one. Could I provide my own character offset for which I want the pixel offset?

**Comment by jonathanong** [comment]
API example?

**Comment by Darker** [comment]
What you you mean by API example?

**Comment by dandv** [comment]
@Darker: please reopen if you're still looking for this feature and can provide an example of some sort. Thanks!
