### ISSUE TITLE
Latest package not available on npm.

### ISSUE THREAD

**Issue by yaru22** [component/textarea-caret-position#22]
Could you publish it on npm or is it going to be available only on component?

**Comment by dominicbarnes** [comment]
I have no idea what the state of this module is on NPM. It doesn't appear like I can publish to it, but the versions that are published on there don't match the tags in this repo.

All in all, it's confusing and I don't know the answer. Sorry :(

If you need to use this module right away, you can always do something like this:

```
{
  "dependencies": {
    "textarea-caret-position": "component/textarea-caret-position#3.0.0"
  }
}
```

**Comment by jonathanong** [comment]
oh shoot. didn't realize someone stole the name on npm!

**Comment by yaru22** [comment]
Thanks @dominicbarnes. I'll try that instead then. Hope you guys can get the name back =)
