### ISSUE TITLE
undefined font-family for textarea

### ISSUE THREAD

**Issue by tetraDB** [component/textarea-caret-position#23]
Its not really a bug as such,
but not having a defined font for the text area meant that the mirror div ended up with a different font to that of the textarea. (Using IE11) the textarea font by default is monospace, but by not being defined its wasn't picked up from the properties, so wasn't applied to the div, and the div just used the body font.

**Comment by jonathanong** [comment]
interesting. mind making a PR?

**Comment by dandv** [comment]
@tetraDB: the text area has had the `Times New Roman` set to it [all along](https://github.com/component/textarea-caret-position/blob/b812d8b281a18933e00f247c434e8c6a3ea1843d/test/index.css).

Can you reproduce and post a screenshot?
