### ISSUE TITLE
Option to return coords of caret bottom

### ISSUE THREAD

**Issue by lolmaus** [component/textarea-caret-position#36]
Hi!

If you want to display a popup/tooltip below caret, you have to account for text field's line height.

Retrieving a calculated value of a DOM element's line height is non-trivial. There's a [library](https://github.com/twolfson/line-height/) that implements a hack similar to what subj does for caret position. Unfortunately, it is unreliable: on Chrome 57 it would report double line height, but single on Firefox 51.

Subj has all the framework required to detect the bottom of the caret. Essentially, the top of the caret + line height.

There's already an undocumented `options` argument which could be used to pass a `bottom` flag.

**Comment by dandv** [comment]
Fixed via af904838644c60a7c48b21ebcca8a533a5967074. Thanks for raising this.

PS: first time I see "subj" on GitHub :)

**Comment by lolmaus** [comment]
Thx!
