### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by ccjmne** [component/textarea-caret-position#39]
There are five pending PR that seem pretty reasonable and well implemented.
Is there a reason not to merge them?

I'd be really interested in using this project (and contribute to it) but I got that sort of ghost-y vibe from it.
Just making sure I'm wrong :)

**Comment by dandv** [comment]
[Yes](https://github.com/component/textarea-caret-position/commit/af904838644c60a7c48b21ebcca8a533a5967074).

Contributions welcome!
